variable "prefix" {}
variable "region" {}
variable "hub_vnet_address_space" {}
variable "hub_subnets" {}
variable "tags" {}
variable "domain_fqdn" {}
variable "name_string_suffix" {}
variable "spoke_vnet_address_space" {}
variable "spoke_subnets" {}