#these files created from details found here https://kubernetes.io/docs/tasks/configure-pod-container/configure-gmsa/
#and here https://github.com/microsoft/Azure-Key-Vault-Plugin-gMSA
#create the custom cred spec for use
apiVersion: windows.k8s.io/v1
kind: GMSACredentialSpec
metadata:
  name: ${gmsa_account_name} #This is an arbitrary name but it will be used as a reference
credspec:
  ActiveDirectoryConfig:
    GroupManagedServiceAccounts:
    - Name: ${gmsa_account_name}   #Username of the GMSA account
      Scope: ${active_directory_netbios_name}  #NETBIOS Domain Name
    - Name: ${gmsa_account_name}   #Username of the GMSA account
      Scope: ${active_directory_domain} #DNS Domain Name
    HostAccountConfig:
      PluginGUID: "{GDMA0342-266A-4D1P-831J-20990E82944F}" #GUID of the key vault plugin
      PluginInput: 'ObjectId="${user_assigned_mi}";SecretUri="${secret_url}"'
      PortableCcgVersion: "1"
  CmsPlugins:
  - ActiveDirectory
  DomainJoinConfig:
    DnsName: ${active_directory_domain}  #DNS Domain Name
    DnsTreeName: ${active_directory_domain} #DNS Domain Name Root
    Guid: ${domain_guid}  #GUID of Domain
    MachineAccountName: ${gmsa_account_name} #Username of the GMSA account
    NetBiosName: ${active_directory_netbios_name}   #NETBIOS Domain Name
    Sid: ${domain_sid} #SID of Domain

---
#Create the Role to read the credspec
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: ${gmsa_account_name} #using the account name as an identifier but not required
rules:
- apiGroups: ["windows.k8s.io"]
  resources: ["gmsacredentialspecs"]
  verbs: ["use"]
  resourceNames: ["${gmsa_account_name}"]

---
#Assign the role to the service accounts
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: allow-default-svc-account-read-on-${gmsa_account_name}
  namespace: default
subjects:
- kind: ServiceAccount
  name: default
  namespace: default
roleRef:
  kind: ClusterRole
  name: ${gmsa_account_name}
  apiGroup: rbac.authorization.k8s.io